[build]
  command = "echo \"const SUPABASE_URL = '$SUPABASE_URL'; const SUPABASE_ANON_KEY = '$SUPABASE_ANON_KEY'; const BUILD_TIME = '$(TZ=America/Santiago date +%Y-%m-%d\\ %H:%M)';\" > config.js"
  publish = "."
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
